"use client"

import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { globalStyles } from './styles/global'

const roboto = Roboto({weight: '700', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

globalStyles()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
